# Generated by Django 5.1.5 on 2025-04-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AES",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AES_name", models.CharField(max_length=100)),
                ("AES_email", models.EmailField(max_length=100)),
            ],
        ),
    ]
